### ISSUE TITLE
1.0.8 causes error

### ISSUE THREAD

**Issue by benstokoe** [svenanders/react-markdown-to-html#1]
When updating to 1.0.8 I get this error:

```
Uncaught TypeError: Expected a function
createWrapper
bind
jQuery.Callbacks.fire
jQuery.Callbacks.self.fireWith
done
jQuery.ajaxTransport.send.callback
```

Seems to be a problem when you required only lodash.bind

Any information on this?

**Comment by svenanders** [comment]
Whoops, that's not good. I'll fix it and ship a new build in a few hours. Thanks for letting me know!

**Comment by svenanders** [comment]
Pushed v1.0.10. Hope it works better!

**Comment by benstokoe** [comment]
Great that works perfectly!
